name: Release ztil
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ztil ${{ github.ref }}
          draft: false
          prerelease: false

  linuxbuild:
    name: build ztil
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install libpcap
        run: sudo apt-get install libpcap-dev
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: build linux version
        run: go build -o ztil -v ./...
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ztil
          asset_name: ztil
          asset_content_type: application/octet-stream

  windowsbuild:
    runs-on: windows-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: build windows version
        run: go build -v -o ztil.exe ./...
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ztil.exe
          asset_name: ztil.exe
          asset_content_type: application/octet-stream